channels:
- conda-forge
dependencies:
- python=3.10.6
- pip<=25.1.1
- pip:
  - mlflow==2.22.0
  - cloudpickle==3.1.1
  - numpy==1.24.3
  - psutil==5.9.4
  - scikit-learn==1.2.1
  - scipy==1.9.3
name: mlflow-env
